// Background Music
export const BACKGROUND_AUDIO = {
    HOME: "/music/whatICallHome.mp3",
    BNW: "/music/theCathedralsThirdCry.mp3",
    BUTTONS: "/music/hopeForAll.mp3",
    CHOICES: "/music/retrospect.mp3",
    TERMINAL: "/music/theCathedralsThirdCry.mp3",
    WIFI_PANEL: "/music/itIsNotFine.mp3",
    WIFI_LOGIN: "/music/whatICallHome.mp3",
    MEDIA: "/music/itIsNotFine.mp3",
    SCROLL: "/music/nowhereSafeSoWhyDoYouScroll.mp3",
    SCROLL_ESCAPE: "/sfx/█.mp3",
    H0M3: "/music/3OClock.mp3",
    CHEATER: "/music/doTheAngelsExist.mp3",
    ROOT_PAGE: "/music/doTheAngelsExist.mp3",
    THE_END_QUESTION: "/music/theSunWontShine.mp3",
    THE_END_FINAL: "/music/ourFinaleOurEndWillIEverSeeYouAgain.mp3",
    MOONLIGHT_NORMAL: "/music/contemplation.mp3",
    MOONLIGHT_RED: "/music/timeIsFake.mp3",
    N404: "/music/3OClock.mp3",
    FILE_CONSOLE: "/music/contempt.mp3",
    DREAM: "/music/daisyBell.mp3",
    COMPUTER: "/music/oldHums.mp3",
    COMPUTER_BOOT: "/music/boot.mp3",
    BSOD: "/music/bsod.mp3",
    CODEX: "/music/ourFinaleOurEndWillIEverSeeYouAgain.mp3",
    BONUS: {
        NO_TIME: "/music/3OClock.mp3",
        NOT_YET: "/music/3OClock.mp3",
        LOCKED: "/music/3OClock.mp3",
    },
} as const;

// Sound Effects
export const SFX_AUDIO = {
    SUCCESS: "/sfx/computerYay.mp3",
    ERROR: "/sfx/computerBoo.mp3",
    ALERT: "/sfx/alert.mp3",
    STATIC: "/sfx/static.mp3",
    HORROR: "/sfx/horror.mp3",
    HEARTBEAT: "/sfx/heartbeat.mp3",
    FILE_DELETE: "/sfx/file_delete.m4a",
    CENSORSHIP: "/sfx/censorship.mp3",
    EGG_CRACK: "/sfx/eggCrack.mp3",
    RESTART: "/sfx/reboot.mp3",
    MOUSE_CLICK: "/sfx/mouseclick.mp3",
    ERROR_POPUP: "/sfx/error.mp3",
} as const;
