export const DISPLAY_NAMES: Record<string, string> = {
    HOME: "Home",
    BNW: "Black & White",
    BUTTONS: "Buttons",
    CHOICES: "Choices",
    TERMINAL: "Terminal",
    WIFI_PANEL: "WiFi Panel",
    WIFI_LOGIN: "WiFi Login",
    MEDIA: "Media",
    SCROLL: "Scroll",
    SCROLL_ESCAPE: "Scroll: Escape",
    H0M3: "H0M3",
    CHEATER: "Cheater",
    ROOT_PAGE: "Root Page (T&C)",
    THE_END_QUESTION: "The End?",
    THE_END_FINAL: "The End [Final]",
    MOONLIGHT_NORMAL: "Moonlight",
    MOONLIGHT_RED: "Moonlight [Blood Moon]",
    N404: "404 (Not Found)",
    FILE_CONSOLE: "File Console",
    DREAM: "Dream",
    COMPUTER: "Computer",
    COMPUTER_BOOT: "Computer Boot",
    BSOD: "BSOD",
    CODEX: "Codex",
    "BONUS.NO_TIME": "Chapter - No Time",
    "BONUS.NOT_YET": "Chapter - Not Yet",
    "BONUS.LOCKED": "Chapter - Locked",
    "BONUS.MAIN": "Chapter Menu",
    "BONUS.I": "Chapter I",
    "BONUS.II": "Chapter II",
    "BONUS.III": "Chapter III",
    "BONUS.IV": "Chapter IV",
    "BONUS.V": "Chapter V",
    "BONUS.VI": "Chapter VI",
    "BONUS.VII": "Chapter VII",
    "BONUS.VIII": "Chapter VIII",
    "BONUS.IX": "Chapter IX",
    "BONUS.X": "Chapter X",
};

// noinspection JSNonASCIINames
export const TRACK_NAMES: Record<string, string> = {
    "whatICallHome.mp3": "What I Call Home",
    "theCathedralsThirdCry.mp3": "The Cathedral's Third Cry",
    "hopeForAll.mp3": "Hope For All",
    "retrospect.mp3": "Retrospect",
    "itIsNotFine.mp3": "It Is Not Fine",
    "nowhereSafeSoWhyDoYouScroll.mp3": "Nowhere Safe, So Why Do You Scroll?",
    "█.mp3": "█",
    "3OClock.mp3": "3 O'Clock",
    "doTheAngelsExist.mp3": "Do The Angels Exist?",
    "theSunWontShine.mp3": "The Sun Won't Shine",
    "ourFinaleOurEndWillIEverSeeYouAgain.mp3": "Our Finale, Our End... Will I Ever See You Again?",
    "contemplation.mp3": "Contemplation",
    "timeIsFake.mp3": "Time Is Fake",
    "contempt.mp3": "Contempt",
    "daisyBell.mp3": "Daisy Bell",
    "oldHums.mp3": "Old Hums",
    "boot.mp3": "Boot",
    "bsod.mp3": "BSOD",
    "dontLeaveMe.mp3": "Don't Leave Me",
    "photosTogether.mp3": "Photos Together",
    "V&X.mp3": "V & X",
    "afuture.mp3": "A Future",
};
