/*
URL[File Console] -> FOR HERE If not cookie[File Unlocked] then 404

A welcome message appears in a console/terminal like page that has a boot animation like old retro device
Has the following commands: cat <>, cd <>, wget <>, ls, help, ofc you know how they work, (There is also secret command "whoami" and "sudo" which aren't in the help aka easter eggs)
Files available:
    - / [Commands available: ls]
    - riddle.pdf [only wget, which downloads the PDF that contains the riddle]
- riddle-hint.txt [cat -> gibberish text that only reading the caps gives the hint, which is to check the riddles EXIF, also wget to get a local file]
- code/ [ls]
- code/robots.txt [cat or wget, contains random shit and then a hidden password to allow access for the pdf]
- code/LETITGROW.tree [FAILS WITH PERM DENIED NOT EVEN SUDO WORKS WITH THIS - wget or cat (doesn't actually exist)]
The riddle when solved hints of using the Konami code in home,
    - If sudo is used “You are NOT in control... IT IS” and aborts 500 with error screen saying “Foolish user attempt to gain control”
  - If whoami is used “No matter what its still you :)” “but... wH0 @R3 ¥0u?”

The following are in public/file-console, riddle.pdf, riddle-hint.txt, robots.txt
*/
'use client';

import { useEffect, useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import styles from '../../styles/FileConsole.module.css';

type Dirent = { name: string; type: 'file' | 'dir'; };
const ROOT_FILES: Dirent[] = [
  { name: 'riddle.pdf', type: 'file' },
  { name: 'riddle-hint.txt', type: 'file' },
  { name: 'code', type: 'dir' }
];
const CODE_FILES: Dirent[] = [
  { name: 'robots.txt', type: 'file' },
  { name: 'LETITGROW.tree', type: 'file' }
];

export default function FileConsole() {
  const router = useRouter();
  const [cwd, setCwd] = useState('/');
  const [history, setHistory] = useState<string[]>([]);
  const [input, setInput] = useState('');
  const [booting, setBooting] = useState(true);
  const consoleRef = useRef<HTMLPreElement>(null);

  useEffect(() => {
    if (!Cookies.get('File Unlocked')) {
      router.replace('/404');
      return;
    }
    setTimeout(() => setBooting(false), 3000); // 3s boot animation
  }, [router]);

  const append = (line: string) => {
    setHistory((h) => [...h, line]);
    setTimeout(() => consoleRef.current?.scrollTo(0, consoleRef.current.scrollHeight), 0);
  };

  const execute = (raw: string) => {
    append(`> ${raw}`);
    const [cmd, ...args] = raw.trim().split(' ');
    switch (cmd) {
      case 'help':
        append('Commands: ls, cat [file], wget [file], cd [dir]');
        break;
      case 'ls':
      {
        const list = cwd === '/'
            ? ROOT_FILES
            : cwd === '/code'
                ? CODE_FILES
                : [];
        list.forEach(f => append(`${f.type === 'dir' ? f.name + '/' : f.name}`));
      }
        break;
      case 'cd':
      {
        const [dir] = args;
        if (cwd === '/' && dir === 'code') setCwd('/code');
        else if (cwd === '/code' && dir === '..') setCwd('/');
        else append('Directory not found');
      }
        break;
      case 'cat':
      {
        const [fn] = args;
        if (cwd === '/' && fn === 'riddle-hint.txt') {
          append('the fitneSsgram pacEr tEsT is a multistage aerobic capacity\n' +
              'test tHat progrEssively gets moRe dIfficult as it continues.\n' +
              '\n' +
              'the twenty-meter pacer test will begin in thirty seconDs.\n' +
              'line up at the start. the running speeD starts sLowly,\n' +
              'but gEts faster each Minute afTer you hear this signal.\n' +
              '\n' +
              '[beEp] a single lAp should be completed each time you hear this sound.\n' +
              '[Ding] remember to run in a straight line, and run as long as possible.\n' +
              '\n' +
              'the second time you fail to complete A lap before the sound,\n' +
              'your test is over. the tesT will begin on the word start.\n' +
              '\n' +
              'on your mark, get reAdy, start.\n');
        } else if (cwd === '/code' && fn === 'robots.txt') {
          append('# robots.txt for http://www.█████████████████.net/\n' +
              '# Generated by TR██.ASSIST.SYSTEM | checksum invalid\n' +
              '\n' +
              'User-agent: *\n' +
              'Disallow: /dev/███\n' +
              'Disallow: /██████/\n' +
              'Disallow: /███/archive/instance(34)/nest/\n' +
              'Disallow: /404/moonlight\n' +
              'Disallow: /ves.el/tmp/data_breach_███\n' +
              'Disallow: /███████████/\n' +
              'Disallow: /consciousness/██████/log/\n' +
              'Disallow: /TREE/███/chamber/█/\n' +
              'Allow: /████/\n' +
              '\n' +
              '# Notes from ██████ before the ██████\n' +
              '# WARNING: DO NOT INTERFACE WITH DIRECTORY █\n' +
              '# %ERR:CMD_FLUX[9A]::redirect(███)→██████\n' +
              '\n' +
              'Crawl-delay: 0.03125\n' +
              '\n' +
              '# THIS IS NOT A SAFE ZONE\n' +
              '# - - - - - - - - - - - - - - -\n' +
              '# timestamp: ████-██-██T██:██:██Z\n' +
              '# recurrence threshold breached at ███ Hz\n' +
              '# interference ID: ∆-ROOT-HUM\n' +
              '# begin /dream_logs\n' +
              '#   repeat::dreams/dreams/dreams/dreams\n' +
              '# connection status: HAHAHAHAHAHAHAHAHAHAHAHAHA\n' +
              '\n' +
              'User-agent: ██████████████████\n' +
              'Allow: /~portal\n' +
              '\n' +
              '# If you are NOT meant to read this... stop.\n' +
              '# If you ARE meant to read this: search the noise.\n' +
              '# That’s where it echoes. It always echoes. It *always* echoes.\n' +
              '\n' +
              '# END: SYSTEM BOUNDARY\n' +
              '\n' +
              '# @@@@ BEGIN AUTH @@@@\n' +
              '# meta-handshake: vessel-key:[VESSEL_31525]\n' +
              '# handoff phrase: pswd_recovery --> XOR(Δ43,Δ31) --> \'bark&rot\'\n' +
              '# Access Key for /███/███/riddle.pdf → \'bark&rot\'\n' +
              '# Don’t say we didn’t warn you\n' +
              '# @@@@ END AUTH @@@@\n');
        } else {
          append('Cannot cat that file');
        }
      }
        break;
      case 'wget':
      {
        const [fn] = args;
        if (cwd === '/' && fn === 'riddle.pdf') {
          append('Downloaded riddle.pdf');
        } else if (cwd === '/' && fn === 'riddle-hint.txt') {
          append('Downloaded riddle-hint.txt');
        } else if (cwd === '/code' && fn === 'robots.txt') {
          append('Downloaded robots.txt');
        } else {
          append('Failed to download');
        }
      }
        break;
      case 'whoami':
        append('No matter what its still you :)');
        append('but... wH0 @R3 ¥0u?');
        break;
      case 'sudo':
        // Trigger 500-style page or modal
        append('You are NOT in control... IT IS');
        setTimeout(() => { throw new Error('Foolish user attempt to gain control'); }, 100);
        break;
      default:
        if (raw.trim()) append(`${cmd}: command not found`);
    }
  };

  return (
      <div className={styles.container}>
      <pre ref={consoleRef} className={styles.console}>
        {booting
            ? 'Booting...\n'
            : history.join('\n')}
      </pre>
        {!booting && (
            <form className={styles.form} onSubmit={(e) => { e.preventDefault(); execute(input); setInput(''); }}>
              <span className={styles.prompt}>{cwd}$</span>
              <input
                  className={styles.input}
                  value={input}
                  onChange={e => setInput(e.target.value)}
                  autoFocus
              />
            </form>
        )}
      </div>
  );
}
